import {
  Blocks,
  ChartColumn,
  Database,
  History,
  LayoutDashboard,
  Settings,
  Smartphone,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

/**
 * Landing-page summary of the Control Center sections (components/landing). Not navigation: the app's
 * navigation is generated by lib/nav.ts and its routes by lib/routes.ts. Phase 5 replaces this list with
 * the new landing sections.
 */
export type SectionTab = "overview" | "copilot" | "capabilities" | "data" | "reports" | "simulator" | "versions" | "settings";

export interface WorkspaceTabMeta {
  value: SectionTab;
  label: string;
  icon: LucideIcon;
}

export const WORKSPACE_TABS: WorkspaceTabMeta[] = [
  { value: "overview", label: "نمای کلی", icon: LayoutDashboard },
  { value: "copilot", label: "دستیار", icon: Sparkles },
  { value: "capabilities", label: "قابلیت‌ها", icon: Blocks },
  { value: "data", label: "عملیات", icon: Database },
  { value: "reports", label: "گزارش‌ها", icon: ChartColumn },
  { value: "simulator", label: "آزمایش ربات", icon: Smartphone },
  { value: "versions", label: "تغییرات و نسخه‌ها", icon: History },
  { value: "settings", label: "تنظیمات", icon: Settings },
];
