import Link from "next/link";
import {
  BarChart3, CalendarDays, Check, CheckCircle2, ChevronLeft, ClipboardList,
  Command, MessageCircleMore, Package, Play, ShieldCheck, ShoppingBag,
  Sparkles, Users, WandSparkles, type LucideIcon,
} from "lucide-react";
import { ThemeToggle } from "@/components/app/theme-toggle";
import { BrandMark } from "./brand-mark";
import { CtaButtons, HeaderCta } from "./cta-buttons";

const categories: { icon: LucideIcon; tag: string; title: string; text: string; examples: string[]; tone: string }[] = [
  { icon: ShoppingBag, tag: "۰۱ / فروش", title: "از ویترین تا سفارش", text: "کاتالوگ، سبد خرید و پیگیری سفارش در همان گفت‌وگویی که مشتری می‌شناسد.", examples: ["محصولات", "سبد خرید", "وضعیت سفارش"], tone: "lg:col-span-2 bg-[#e4f3f8] dark:bg-[#102d41]" },
  { icon: CalendarDays, tag: "۰۲ / عملیات", title: "کارهای روزانه، مرتب", text: "ثبت‌نام رویداد، رزرو، فرم و صف انتظار با قواعد مشخص.", examples: ["رویدادها", "رزرو", "فرم‌ها"], tone: "bg-[#f5eee5] dark:bg-[#302a27]" },
  { icon: Users, tag: "۰۳ / تیم", title: "همه در جریان", text: "نقش‌های کارکنان، اعلان‌ها و گزارش‌های زمان‌بندی‌شده برای تیم.", examples: ["نقش‌ها", "اعلان", "گزارش دوره‌ای"], tone: "bg-[#eef0ff] dark:bg-[#202942]" },
  { icon: BarChart3, tag: "۰۴ / بینش", title: "از داده تا تصمیم", text: "گزارش عملکرد، تحلیل صفحه‌گسترده و پاسخ به پرسش‌های کسب‌وکار.", examples: ["گزارش‌ها", "تحلیل فایل", "دستیار مالک"], tone: "bg-[#e9f4ed] dark:bg-[#19352e]" },
  { icon: MessageCircleMore, tag: "۰۵ / ارتباط با مشتری", title: "پاسخ‌گویی همیشه در دسترس", text: "منوی گفتگو، اطلاعات کاربردی و پیگیری درخواست‌ها در تلگرام.", examples: ["منوی گفتگو", "پرسش‌های متداول", "درخواست‌ها"], tone: "lg:col-span-2 bg-[#f4eaf0] dark:bg-[#322638]" },
];

const steps: { number: string; icon: LucideIcon; title: string; text: string }[] = [
  { number: "۰۱", icon: MessageCircleMore, title: "کسب‌وکارتان را تعریف کنید", text: "به زبان خودتان بگویید چه می‌فروشید، چه خدمتی دارید و مشتری چطور باید با شما کار کند." },
  { number: "۰۲", icon: ShieldCheck, title: "پیشنهاد را بررسی کنید", text: "قابلیت‌ها و رفتار ربات را ببینید، در شبیه‌ساز امتحان کنید و بعد نسخه را تأیید کنید." },
  { number: "۰۳", icon: Play, title: "منتشر کنید و اداره کنید", text: "همان ربات تلگرام با نسخهٔ تازه کار می‌کند؛ سفارش‌ها، مشتریان و عملکرد را از پنل دنبال کنید." },
];

const faq = [
  ["برای ساخت ربات باید برنامه‌نویسی بلد باشم؟", "خیر. کسب‌وکارتان را توصیف می‌کنید، پیشنهاد ساخته‌شده را بررسی می‌کنید و پیش از انتشار در شبیه‌ساز امتحانش می‌کنید."],
  ["آیا هر پیام مشتری به هوش مصنوعی فرستاده می‌شود؟", "خیر. هوش مصنوعی در ساخت و تغییر پیکربندی و برخی ابزارهای تحلیلی کمک می‌کند. کارهای روزمرهٔ ربات با قواعد نسخهٔ منتشرشده اجرا می‌شوند."],
  ["اگر بخواهم رفتار ربات را تغییر بدهم چه؟", "می‌توانید تغییر را درخواست کنید، نتیجه را پیش از انتشار ببینید و در صورت نیاز به نسخه‌های قبلی برگردید."],
  ["می‌توانم پیش از اتصال به تلگرام آن را ببینم؟", "بله. شبیه‌ساز پنل به شما امکان می‌دهد مسیر گفت‌وگو را پیش از انتشار و اتصال واقعی آزمایش کنید."],
];

function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) {
  return <div className="max-w-2xl"><p className="mb-4 text-xs font-bold tracking-wider text-[#087e91] dark:text-[#68d5dc]">{eyebrow}</p><h2 className="text-3xl leading-[1.45] font-black tracking-tight text-[#102940] sm:text-4xl dark:text-white">{title}</h2><p className="mt-5 text-base leading-8 text-[#547082] dark:text-[#a7c0cf]">{text}</p></div>;
}

function FlowPreview() {
  return <div className="relative mx-auto w-full max-w-[570px] px-1 pb-8 pt-8 sm:px-4" aria-label="پیش‌نمایش نمایشی ساخت ربات و پنل کنترل">
    <div className="absolute inset-x-8 top-7 h-[78%] rounded-[3rem] bg-[#d0edf0]/70 blur-3xl dark:bg-[#0b607c]/30" aria-hidden="true" />
    <div className="relative rounded-[2rem] border border-white/70 bg-white/65 p-3 shadow-[0_25px_80px_-36px_rgba(15,57,81,.4)] backdrop-blur-sm sm:p-5 dark:border-white/10 dark:bg-[#122b40]/80">
      <div className="mb-3 flex items-center justify-between gap-2 rounded-2xl bg-[#f4f8f8] px-4 py-3 text-xs text-[#617b8c] dark:bg-white/5 dark:text-[#adcad8]"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-[#19b3a7]" /> مسیر ساخت ربات</span><span dir="ltr" className="font-mono text-[10px]">BOTFORGE / PREVIEW</span></div>
      <div className="space-y-3">
        <div className="rounded-2xl border border-[#dae7e8] bg-white px-4 py-4 shadow-sm dark:border-white/10 dark:bg-[#15354d]"><div className="mb-3 flex items-center gap-2 text-[11px] font-bold text-[#138999] dark:text-[#78d5dc]"><span className="flex size-6 items-center justify-center rounded-lg bg-[#e4f5f4] dark:bg-[#155063]"><Command className="size-3.5" /></span> توضیح شما</div><p className="text-sm leading-7 text-[#2a4857] dark:text-[#daedf0]">«برای کارگاه‌ها ثبت‌نام بگیر؛ ظرفیت و فهرست انتظار را هم مدیریت کن.»</p></div>
        <div className="flex items-center gap-3 px-3 text-[11px] font-bold text-[#399e9c] dark:text-[#85d5d5]"><div className="h-px flex-1 bg-[#b9dddf] dark:bg-[#346274]" /><WandSparkles className="size-4" /> بات‌فورج می‌سازد <div className="h-px flex-1 bg-[#b9dddf] dark:bg-[#346274]" /></div>
        <div className="grid gap-3 sm:grid-cols-[1fr_1.08fr]">
          <div className="overflow-hidden rounded-2xl bg-[#153a52] text-white shadow-lg"><div className="flex items-center gap-2 bg-[#214d67] px-3 py-3"><span className="flex size-7 items-center justify-center rounded-full bg-[#6fc5d1] text-[#12394d]"><MessageCircleMore className="size-4" /></span><div><p className="text-[11px] font-bold">ربات کارگاه شما</p><p className="text-[10px] text-[#b4d0dd]">نمونهٔ گفتگو</p></div></div><div className="space-y-2 px-3 py-4 text-[11px] leading-6"><div className="mr-auto max-w-[90%] rounded-2xl rounded-tl-sm bg-[#2e5871] px-3 py-2">سلام! برای کدام کارگاه می‌خواهید ثبت‌نام کنید؟</div><div className="ml-auto w-fit rounded-2xl rounded-tr-sm bg-[#388aa0] px-3 py-1.5">کارگاه سفال‌گری</div><div className="mr-auto max-w-[90%] rounded-2xl rounded-tl-sm bg-[#2e5871] px-3 py-2">یک جای خالی باقی مانده است. ثبت‌نام را ادامه دهیم؟</div></div></div>
          <div className="rounded-2xl border border-[#dce8e8] bg-white p-3 shadow-lg dark:border-white/10 dark:bg-[#193a4c]"><div className="mb-3 flex items-center justify-between text-xs"><span className="font-bold text-[#183b4d] dark:text-white">مرکز کنترل</span><span className="rounded-full bg-[#def3e8] px-2 py-0.5 text-[10px] font-bold text-[#167960] dark:bg-[#16493f] dark:text-[#79dfbe]">نسخهٔ فعال</span></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f0f7f7] p-3 dark:bg-white/5"><span className="block text-[10px] text-[#6e8896] dark:text-[#9cbdcc]">ثبت‌نام‌ها</span><strong className="mt-1 block text-xl text-[#143e54] dark:text-white">۲۴</strong></div><div className="rounded-xl bg-[#f0f7f7] p-3 dark:bg-white/5"><span className="block text-[10px] text-[#6e8896] dark:text-[#9cbdcc]">جای خالی</span><strong className="mt-1 block text-xl text-[#143e54] dark:text-white">۳</strong></div></div><div className="mt-3 flex items-center gap-2 rounded-xl border border-[#e3eded] px-2.5 py-2 text-[10px] text-[#436579] dark:border-white/10 dark:text-[#c7dfe6]"><Check className="size-3.5 text-[#0d898c]" /> فهرست انتظار خودکار</div><div className="mt-2 flex items-center gap-2 rounded-xl border border-[#e3eded] px-2.5 py-2 text-[10px] text-[#436579] dark:border-white/10 dark:text-[#c7dfe6]"><Check className="size-3.5 text-[#0d898c]" /> گزارش عملکرد</div></div>
        </div>
      </div>
    </div><span className="absolute -bottom-1 left-4 rounded-full border border-[#dce9e7] bg-white px-3 py-1 text-[10px] font-semibold text-[#718c98] shadow-sm dark:border-white/10 dark:bg-[#16384c] dark:text-[#b3d0da]">داده‌های نمایشی</span>
  </div>;
}

function UseCasePreview({ kind }: { kind: "workshop" | "shop" | "form" }) {
  if (kind === "workshop") return <div className="space-y-2 rounded-2xl bg-white/80 p-3 text-xs dark:bg-[#17364a]"><div className="flex items-center justify-between"><span>کارگاه سفال‌گری</span><span className="rounded-full bg-[#dcf5ec] px-2 py-1 text-[#13765e] dark:bg-[#16483f] dark:text-[#89d8be]">۳ جای خالی</span></div><div className="h-2 overflow-hidden rounded-full bg-[#e7eeee] dark:bg-white/10"><div className="h-full w-4/5 rounded-full bg-[#20a4a5]" /></div><span className="text-[#708999] dark:text-[#aac7d3]">ظرفیت ۲۰ نفر · فهرست انتظار فعال</span></div>;
  if (kind === "shop") return <div className="flex items-center gap-3 rounded-2xl bg-white/80 p-3 text-xs dark:bg-[#17364a]"><span className="flex size-12 items-center justify-center rounded-xl bg-[#e4f0f5] text-[#177b9c] dark:bg-[#27536a]"><Package className="size-6" /></span><div className="min-w-0 flex-1"><p className="font-bold">سفارش تازه</p><p className="mt-1 text-[#718a99] dark:text-[#aac7d3]">۲ محصول · آمادهٔ بررسی</p></div><CheckCircle2 className="size-5 text-[#1b9c88]" /></div>;
  return <div className="space-y-2 rounded-2xl bg-white/80 p-3 text-xs dark:bg-[#17364a]"><div className="flex items-center justify-between"><span className="font-bold">درخواست مشاوره</span><span className="text-[#178ca1] dark:text-[#7bd5df]">جدید</span></div><div className="h-2 w-full rounded-full bg-[#e7eeee] dark:bg-white/10" /><div className="h-2 w-2/3 rounded-full bg-[#e7eeee] dark:bg-white/10" /><span className="block text-[#718a99] dark:text-[#aac7d3]">اطلاعات مشتری ثبت شد</span></div>;
}

export function LandingPage() {
  return <div className="min-h-dvh overflow-x-clip bg-[#f8faf8] text-[#102940] dark:bg-[#091e30] dark:text-[#f1f8fa]">
    <a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:rounded-xl focus:bg-white focus:px-4 focus:py-3 focus:text-[#102940]">رفتن به محتوای اصلی</a>
    <header className="sticky top-0 z-40 border-b border-[#dce8e8]/80 bg-[#f8faf8]/90 backdrop-blur-xl dark:border-white/10 dark:bg-[#091e30]/90"><nav aria-label="ناوبری اصلی" className="mx-auto flex h-16 w-full max-w-7xl items-center justify-between gap-3 px-5 sm:h-20 sm:px-8 lg:px-10"><BrandMark /><div className="hidden items-center gap-7 text-sm font-medium text-[#5c7584] lg:flex dark:text-[#abc6d2]"><a href="#features" className="hover:text-[#057e98] dark:hover:text-white">قابلیت‌ها</a><a href="#how" className="hover:text-[#057e98] dark:hover:text-white">چگونه کار می‌کند</a><a href="#uses" className="hover:text-[#057e98] dark:hover:text-white">کاربردها</a><a href="#faq" className="hover:text-[#057e98] dark:hover:text-white">پرسش‌ها</a></div><div className="flex items-center gap-2"><ThemeToggle /><HeaderCta /></div></nav></header>
    <main id="main">
      <section className="relative isolate overflow-hidden border-b border-[#e3eceb] dark:border-white/10"><div aria-hidden="true" className="absolute -top-28 -left-28 size-[30rem] rounded-full bg-[#c8ebed]/50 blur-3xl dark:bg-[#0b5370]/20" /><div className="relative mx-auto grid w-full max-w-7xl items-center gap-10 px-5 pb-20 pt-14 sm:px-8 sm:pt-20 lg:grid-cols-[.95fr_1.05fr] lg:gap-12 lg:px-10 lg:py-28"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#cfe8e9] bg-white px-3 py-1.5 text-xs font-bold text-[#137c90] shadow-sm dark:border-[#276077] dark:bg-[#15384c] dark:text-[#82d8df]"><Sparkles className="size-3.5" /> سیستم‌عامل کسب‌وکار در تلگرام</div><h1 className="max-w-2xl text-[clamp(2.6rem,5.1vw,5rem)] leading-[1.25] font-black tracking-[-0.035em] text-[#102c41] dark:text-white">کسب‌وکارتان را بگویید.<br /><span className="text-[#0a8aa0] dark:text-[#65d3dc]">رباتش را بسازید.</span></h1><p className="mt-7 max-w-xl text-base leading-9 text-[#526d7e] sm:text-lg dark:text-[#afc9d6]">از ثبت‌نام و سفارش تا مدیریت تیم و گزارش‌ها؛ بات‌فورج از توضیح شما یک ربات تلگرام می‌سازد که می‌توانید رفتار آن را پیش از انتشار بررسی و آزمایش کنید.</p><div className="mt-8"><CtaButtons /></div><div className="mt-9 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-[#66808e] dark:text-[#a6c3d0]"><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-[#18a59c]" /> ساخت با زبان طبیعی</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-[#18a59c]" /> آزمایش پیش از انتشار</span><span className="flex items-center gap-1.5"><CheckCircle2 className="size-4 text-[#18a59c]" /> نسخه‌های قابل بازگشت</span></div></div><FlowPreview /></div></section>
      <section id="features" aria-label="قابلیت‌ها" className="scroll-mt-24 mx-auto w-full max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><Heading eyebrow="از یک گفتگو تا یک سیستم منسجم" title="همهٔ بخش‌های کسب‌وکار، در جای درست خود." text="هر ربات از قابلیت‌هایی شکل می‌گیرد که برای کار شما لازم است. این‌ها نمونه‌ای از ابزارهایی هستند که می‌توانید کنار هم داشته باشید." /><div className="mt-11 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{categories.map(({ icon: Icon, tag, title, text, examples, tone }) => <article key={title} className={`group flex min-h-[270px] flex-col rounded-[1.8rem] border border-black/5 p-6 transition-transform duration-300 motion-reduce:transition-none hover:-translate-y-1 motion-reduce:hover:translate-y-0 sm:p-8 dark:border-white/5 ${tone}`}><div className="mb-auto flex items-start justify-between"><span className="text-xs font-bold text-[#4a7180] dark:text-[#a8c9d4]">{tag}</span><span className="flex size-11 items-center justify-center rounded-2xl bg-white/75 text-[#0a7f96] shadow-sm dark:bg-white/10 dark:text-[#83d5df]"><Icon className="size-5" /></span></div><h3 className="mt-8 text-xl font-extrabold text-[#153247] dark:text-white">{title}</h3><p className="mt-2 max-w-md text-sm leading-7 text-[#5a7482] dark:text-[#b5cbd3]">{text}</p><div className="mt-5 flex flex-wrap gap-2">{examples.map(e => <span key={e} className="rounded-full border border-white/75 bg-white/65 px-3 py-1 text-[11px] font-semibold text-[#507080] dark:border-white/10 dark:bg-white/5 dark:text-[#c5d9df]">{e}</span>)}</div></article>)}</div></section>
      <section id="how" aria-label="چگونه کار می‌کند" className="scroll-mt-24 bg-[#eaf2f1] py-20 dark:bg-[#102a3c] lg:py-28"><div className="mx-auto w-full max-w-7xl px-5 sm:px-8 lg:px-10"><Heading eyebrow="ساده، اما قابل کنترل" title="از ایده تا ربات فعال، در سه گام." text="شما دربارهٔ کسب‌وکار تصمیم می‌گیرید. بات‌فورج ساخت، آزمایش و نگهداری رفتار ربات را در یک مسیر روشن کنار هم می‌گذارد." /><ol className="mt-11 grid gap-4 md:grid-cols-3">{steps.map(({ number, icon: Icon, title, text }) => <li key={number} className="rounded-[1.7rem] border border-[#d8e7e5] bg-white p-7 shadow-[0_15px_40px_-34px_rgba(15,57,81,.45)] dark:border-white/10 dark:bg-[#16374a]"><div className="mb-8 flex items-start justify-between"><span className="font-mono text-xs font-bold tracking-widest text-[#138da0] dark:text-[#79d8df]">{number} / ۰۳</span><Icon className="size-6 text-[#149ca3] dark:text-[#82dadd]" /></div><h3 className="text-lg font-extrabold text-[#163448] dark:text-white">{title}</h3><p className="mt-3 text-sm leading-8 text-[#5d7886] dark:text-[#b4cad4]">{text}</p></li>)}</ol></div></section>
      <section id="uses" aria-label="کاربردها" className="scroll-mt-24 mx-auto w-full max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><Heading eyebrow="برای کارهای واقعی" title="یک بستر؛ مسیرهای کاری متفاوت." text="چند نمونه از کاری که می‌توانید با قابلیت‌های بات‌فورج انجام دهید. پیش‌نمایش‌های زیر دادهٔ نمایشی دارند." /><div className="mt-11 grid gap-5 lg:grid-cols-3">{([
        { kind: "workshop" as const, icon: CalendarDays, name: "کارگاه و رویداد", text: "ثبت‌نام، ظرفیت، لغو و جابه‌جایی خودکار از فهرست انتظار.", color: "bg-[#eff5e9] dark:bg-[#1d3934]" },
        { kind: "shop" as const, icon: ShoppingBag, name: "فروشگاه کوچک", text: "نمایش محصول، سبد خرید، ثبت سفارش و پیگیری وضعیت.", color: "bg-[#e7f2f7] dark:bg-[#15364b]" },
        { kind: "form" as const, icon: ClipboardList, name: "فرم و درخواست", text: "دریافت اطلاعات مشتری و پیگیری درخواست در یک جریان گفتگو.", color: "bg-[#f5edf1] dark:bg-[#372b3b]" },
      ]).map(({ kind, icon: Icon, name, text, color }) => <article key={kind} className={`rounded-[1.8rem] p-6 sm:p-7 ${color}`}><div className="flex size-12 items-center justify-center rounded-2xl bg-white/80 text-[#0f8ca0] dark:bg-white/10 dark:text-[#8adddf]"><Icon className="size-6" /></div><h3 className="mt-7 text-xl font-extrabold text-[#17384b] dark:text-white">{name}</h3><p className="mt-2 min-h-16 text-sm leading-7 text-[#5a7786] dark:text-[#b5cbd5]">{text}</p><div className="mt-7"><UseCasePreview kind={kind} /></div></article>)}</div></section>
      <section aria-label="مرکز کنترل کسب‌وکار" className="bg-[#102e42] py-20 text-white dark:bg-[#071726] lg:py-28"><div className="mx-auto grid w-full max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:px-10"><div><p className="mb-4 text-xs font-bold tracking-wider text-[#74d5db]">مرکز کنترل کسب‌وکار</p><h2 className="text-3xl leading-[1.5] font-black sm:text-4xl">ربات در تلگرام کار می‌کند.<br />شما تصویر کامل را می‌بینید.</h2><p className="mt-6 max-w-lg text-base leading-9 text-[#b8ced8]">از وضعیت نسخه و قابلیت‌ها تا سفارش‌ها، گزارش‌ها و اعضای تیم؛ ابزار مدیریت در یک پنل کنار هم قرار می‌گیرند.</p><ul className="mt-8 grid gap-3 text-sm text-[#d8e8ec] sm:grid-cols-2">{["شاخص‌ها و فعالیت اخیر", "داده‌ها و سفارش‌ها", "شبیه‌ساز گفتگو", "تاریخچهٔ نسخه‌ها"].map(item => <li className="flex items-center gap-2" key={item}><Check className="size-4 text-[#73dbca]" />{item}</li>)}</ul></div><div className="rounded-[2rem] border border-white/15 bg-[#1d4257] p-3 shadow-[0_35px_75px_-35px_rgba(0,0,0,.55)] sm:p-5"><div className="flex items-center justify-between border-b border-white/10 px-3 pb-4 text-xs text-[#b7d0dc]"><span className="flex items-center gap-2"><BarChart3 className="size-4 text-[#7bd8db]" /> داشبورد کارگاه</span><span className="rounded-full bg-[#286558] px-2.5 py-1 text-[#b8f3dd]">فعال</span></div><div className="mt-4 grid grid-cols-3 gap-2 sm:gap-3">{[["ثبت‌نام", "۲۴"], ["در انتظار", "۵"], ["رویدادها", "۳"]].map(([label, value]) => <div key={label} className="rounded-xl bg-[#285169] p-3 sm:p-4"><span className="text-[10px] text-[#b2cad5] sm:text-xs">{label}</span><strong className="mt-3 block text-xl sm:text-2xl">{value}</strong></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-[1.25fr_.75fr]"><div className="min-w-0 rounded-xl bg-[#285169] p-4"><div className="mb-6 flex items-center justify-between text-xs"><span>روند ثبت‌نام</span><BarChart3 className="size-4 text-[#83d7dc]" /></div><div className="flex h-20 items-end gap-2" aria-hidden="true">{[35, 55, 45, 72, 60, 87, 100].map((h, i) => <span key={i} style={{ height: `${h}%` }} className="flex-1 rounded-t-sm bg-[#58c6c5]" />)}</div></div><div className="rounded-xl bg-[#285169] p-4"><p className="text-xs">قابلیت‌های فعال</p><div className="mt-5 space-y-3 text-[11px] text-[#cee2e9]"><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-[#78dcc4]" /> رویدادها</p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-[#78dcc4]" /> گزارش‌ها</p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-[#78dcc4]" /> فرم‌ها</p></div></div></div><p className="px-2 pt-3 text-[10px] text-[#9fc1d0]">نمایش نمونه با دادهٔ آزمایشی</p></div></div></section>
      <section id="faq" aria-label="پرسش‌های متداول" className="scroll-mt-24 mx-auto grid w-full max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.75fr_1.25fr] lg:gap-20 lg:px-10 lg:py-28"><Heading eyebrow="پرسش‌های متداول" title="پیش از شروع بدانید." text="آنچه دربارهٔ ساخت، اجرای روزمره و تغییر ربات باید بدانید." /><div className="space-y-3">{faq.map(([q, a]) => <details key={q} className="group rounded-2xl border border-[#dce7e6] bg-white px-5 py-1 open:shadow-sm dark:border-white/10 dark:bg-[#143247]"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-4 text-sm font-bold text-[#17384c] marker:hidden sm:text-base dark:text-white">{q}<ChevronLeft className="size-4 shrink-0 text-[#4c98a6] transition-transform group-open:-rotate-90 motion-reduce:transition-none" /></summary><p className="pb-5 text-sm leading-8 text-[#5e7887] dark:text-[#b7cdd6]">{a}</p></details>)}</div></section>
      <section className="px-5 pb-16 sm:px-8 lg:px-10"><div className="relative mx-auto flex w-full max-w-7xl flex-col items-start gap-6 overflow-hidden rounded-[2rem] bg-[#e0eff0] p-8 sm:p-12 lg:flex-row lg:items-center lg:justify-between lg:p-16 dark:bg-[#173d50]"><div aria-hidden="true" className="absolute -left-20 -top-28 size-72 rounded-full border-[36px] border-white/25" /><div className="relative"><p className="mb-3 text-xs font-bold text-[#0f8394] dark:text-[#79d8da]">شروع از یک توضیح</p><h2 className="max-w-xl text-2xl leading-[1.5] font-black text-[#15374a] sm:text-3xl dark:text-white">ایدهٔ ربات شما از همین‌جا شکل می‌گیرد.</h2><p className="mt-2 text-sm leading-7 text-[#5d7986] dark:text-[#b6d0da]">کسب‌وکارتان را تعریف کنید و اولین نسخه را بسازید.</p></div><div className="relative"><CtaButtons /></div></div></section>
    </main>
    <footer className="border-t border-[#dfe9e8] px-5 py-8 dark:border-white/10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 sm:flex-row sm:items-center"><BrandMark /><div className="flex flex-wrap gap-5 text-xs text-[#617d89] dark:text-[#a5c0cb]"><a href="#features" className="hover:underline">قابلیت‌ها</a><a href="#how" className="hover:underline">نحوهٔ کار</a><a href="#faq" className="hover:underline">پرسش‌ها</a><Link href="/login" className="hover:underline">ورود</Link></div><span dir="ltr" className="text-xs text-[#829aa4] dark:text-[#87a7b4]">© BotForge</span></div></footer>
  </div>;
}
